server:
  port: 8052

zk:
  url: 127.0.0.1:2181
  timeout: 3000

spring:
  ################################
  # Redis配置
  ################################
  redis:
    host: demo.redis.cn
    port: 6379
    password: 123456