server:
  port: 8080

###############
#聊天服务配置
###############
chat:
  server:
    port: 18080

###############
#ZK服务配置
###############
zk:
  url: 127.0.0.1:2181
  timeout: 3000

spring:
  ################################
  # Redis配置
  ################################
  redis:
    host: demo.redis.cn
    port: 6379
    password: 123456