server:
  port: 8070

###############
#聊天服务配置
###############
chat:
  server:
    port: 18070

###############
#ZK服务配置
###############
zk:
  url: 127.0.0.1:2181
  timeout: 3000

spring:
  ################################
  # Redis配置
  ################################
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379